spring:
  application:
    name: LibraryManagementSystem
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/LibraryManager
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: info