spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: LibraryManagementSystem
  datasource:
    username: ${USER}
    password: ${PASSWORD}
    url: jdbc:postgresql://localhost:5432/LibraryManager
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/main-changelog.xml


logging:
  level:
    org.springframework: info

