spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: LibraryManagementSystem
  mvc:
    hiddenmethod:
      filter:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    username: ${USER}
    password: ${PASSWORD}
    url: jdbc:postgresql://localhost:5432/LibraryManager
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/main-changelog.xml

logging:
  level:
    org.springframework: info
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: user
    password: password
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/main-changelog.xml
logging:
  level:
    org.springframework: debug